{{- if .Values.sidekiq.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canine.fullname" . }}-sidekiq
  labels:
    {{- include "canine.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.sidekiq.replicaCount }}
  selector:
    matchLabels:
      {{- include "canine.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "canine.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z {{ include "canine.postgresql.host" . }} {{ include "canine.postgresql.port" . }}; do echo waiting for db; sleep 2; done;']
        - name: wait-for-redis
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z {{ include "canine.redis.host" . }} {{ include "canine.redis.port" . }}; do echo waiting for redis; sleep 2; done;']
      containers:
        - name: sidekiq
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["bundle", "exec", "sidekiq"]
          resources:
            {{- toYaml .Values.sidekiq.resources | nindent 12 }}
          env:
            - name: RAILS_ENV
              value: {{ .Values.rails.env }}
            - name: RAILS_LOG_LEVEL
              value: {{ .Values.rails.logLevel }}
            - name: RAILS_LOG_TO_STDOUT
              value: "true"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "canine.fullname" . }}-secret
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "canine.fullname" . }}-secret
                  key: redis-url
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "canine.fullname" . }}-secret
                  key: secret-key-base
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "canine.fullname" . }}-secret
                  key: rails-master-key
            {{- with .Values.rails.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: storage
              mountPath: /rails/storage
            - name: tmp
              mountPath: /rails/tmp
      volumes:
        - name: storage
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "canine.fullname" .) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}